stages:
    - build
    - test

build:web:
    image: node:10.13.0
    stage: build
    script:
        - "cd OnlineRecLeague.Web"
        - "npm ci"
        - "npm run build"
    artifacts:
        paths:
            - OnlineRecLeague.Web/dist

build:service:
    image: mcr.microsoft.com/dotnet/core/sdk:2.2
    stage: build
    script:
        - "dotnet publish OnlineRecLeague.Service -o ../service"
        - "dotnet run --CreateSchema=true --SchemaOutput=../service"
    artifacts:
        name: "$CI_JOB_NAME"
        paths:
            - service

test:
    image: mcr.microsoft.com/dotnet/core/sdk:2.2
    stage: test
    script:
        - "dotnet test OnlineRecLeague.Tests"